### ISSUE TITLE
Starting a new game in Chronicles of Myrtana throws an error with the latest version of GD3D11

### ISSUE THREAD

**Issue by SaulMyers** [kirides/GD3D11#149]
**Describe the bug**
With the latest version (i.e. I'm cloning the repo and compiling), when you start a new game in Chronicles of Myrtana then it will crash with the following error:

![image](https://github.com/kirides/GD3D11/assets/97944650/7927fb1f-579a-4cb0-b3ca-c2dd30f18758)

I suspect it also broke the trigger when moving to act 2 - the game world just got stuck and I couldn't progress. This seemed to happen after moving to assimp v1.43, but I don't know if that has anything to do with it.

Note that the original G2 seems to work fine with the latest version.

**To Reproduce**
1. Launch the Game
2. Select 'New Game' and yes to continue, it'll crash during the load screen.

**Expected behavior**
A cutscene should play and the game should start

**Please complete the following information):**
 - Graphics card: NVIDIA RTX3060 TI
 - Gothic version: Chronicles of Myrtana.

**Comment by kirides** [comment]
The Bink player part was re-implemented using shaders by SaiyansKing iirc. this may have something to do with this.

I will take a look at it.

**Comment by kirides** [comment]
The mod works properly with the latest Nightly releases (https://github.com/kirides/GD3D11/releases/tag/nightly)
I played through the whole mod on my `AMD 7900 XTX` with this Renderer ( a slightly older version though) and all, videos spells and regular gameplay work flawlessly.


Please refer to Nightly-releases for now, as i haven't been able to pin point new "release"-versions yet, due to not working on the renderer as active anymore.
This might change in a few months, but only time will tell.
