### ISSUE TITLE
Why are there positives on virustotal?

### ISSUE THREAD

**Issue by ChillzzAtGITHUB** [kirides/GD3D11#157]
The scan of the file:
https://www.virustotal.com/gui/file/e60835c857927ac94269d4e7247517b20ffb0fb87ea2821eb8da532eca107cac/detection

**Comment by kirides** [comment]
Because the way the renderer works it hooks into a games code and overrides it in memory. That's exactly what a virus would do.

But that's a so called "false positive".
The renderer does not steal any data or does any other malicious things.

At least not with code found in this repository and releases published on it.

**Comment by ChillzzAtGITHUB** [comment]
Thanks for the fast answer :)
