### ISSUE TITLE
Gothic2: start menu music theme stops playing when loading a game with recent 17.7-dev15-fix1

### ISSUE THREAD

**Issue by stefson** [Kirides/GD3D11#26]
I just noticed this when updating the GD3D11 renderer: the menu music theme stops playing instantly when loading a game. Instead, it should keep on playing until the game is loaded, and then slowly fade out. 

not affected: 17.7-dev11-fix2
affected: 17.7-dev15-fix1

I will try to find the exact version this broke and report back in case.

**Comment by Kirides** [comment]
Thats on purpose.

because it never "slowly fades out" but is absudly loud for a long period of time.
This is a fix implemented from Union into the renderer.

**Comment by stefson** [comment]
ehr, okay? I thought this project was not about bug fixing the game, but to add the new d3d11 renderer only?

**Comment by Kirides** [comment]
so? There are a few fixes implemented which make the renderer run smoother by modifying the game.

This is the single only fix that is not a performance fix, but a "god why is this so loud" fix.

Also i might not even consider making this an on/off option, just because it is a 20 second thing which only happens if you start the game the first time, any subsequent loading screens do not have the sound.
If someone wants to listen to the soundtrack... well, just stay in the main menu after starting up the game?

Especially content creators wanted this included, because of that huge audio volume difference.
And most content viewers i talked to appreciated the fix.
