### ISSUE TITLE
G1 - WorldShadowRangeScale latest version - opinion :),  question about "rain"

### ISSUE THREAD

**Issue by donmarczello** [Kirides/GD3D11#29]
In the latest version, the problem has been fixed with WorldShadowRangeScale on loading
but

I have the impression that the shadows "flicker more".  --> Please check because maybe it seems to me

---------------------------------------

Second question about rain:

Isn't that a bug that
it only rains at a certain time (3:00 p.m. - 4:00 p.m.) in game
Could it not rain **"randomly**" at different times?
It would be realistic.

Regards and wait for a reply.

**Comment by Kirides** [comment]
What do you mean exactly with "flicker more" ? What is the Shadowmap size you picked?
Smaller Shadowmaps will generally look worse than larger ones.
Generally the best looking would be currently 16384.

Sadly, because i am not knowledgable enough to implement CSM or VSM for better resource utilisation and cleaner shadows.

----

I don't know why gothic tells its renderer to rain exactly at 4pm every single day.

**Comment by donmarczello** [comment]
Shadowmap size 2048 mainly, but I'm throwing a movie https://drive.google.com/file/d/19pSzJK6k9UvzuQ6vSQlq8gsjrFFLroyQ/view - download and open
**Maybe is everything OK?**

**Comment by Kirides** [comment]
it looks exactly like it should.

2048 is way too low for the current shadowmapping implementation to look _good_

In a proper implementation of shadowmaps, 2048 could be more than sufficient to look fine, but we have none.
