### ISSUE TITLE
Chapter screen missing

### ISSUE THREAD

**Issue by yurijgera** [Kirides/GD3D11#32]
Clean Gothic1 install, with gothic_patch_108k.exe, gothic1_playerkit-1.08k.exe, Gothic1_PlayerKit-2.8.exe, G1Classic-SystemPack-1.8.exe
Without GD3D11 the chapter screen is displayed.
With GD3D11 installed, the chapter screen is missing / not visible.
![ChapterMissing](https://user-images.githubusercontent.com/41427485/102939196-1d35de80-44ae-11eb-9424-02a3c54743e1.jpg)

**Comment by Kirides** [comment]
This happens due to missing alphachannel on the texture.
This occurs in a few G2 mods awell.

Might aswell be enough to find an apropriate place in the code to just override the alpha to be 0xFF for cases where it's missing.

i don't have the time to research where to put it and to test it though.
Might take a while unless someone else picks this issue up.

**Comment by Kirides** [comment]
Might already be fixed with current release
