### ISSUE TITLE
Gothic2.exe - 0xc0000005 error 

### ISSUE THREAD

**Issue by kubachimaru** [Kirides/GD3D11#37]
I cant use any patch later than GD3D11-17.7-dev8 because i cant open game - error 0xc0000005 appear (Windows 7 Lenovo Ideapad Y700). Why is this so ? If i paste latest patch this error is showing up, but when back to patch 17.7-dev8 game is working with no problems...
![błąd](https://user-images.githubusercontent.com/80598343/111077676-37ea8300-84f2-11eb-80de-b4a6f1e1ff20.png)

**Comment by Kirides** [comment]
I do not support windows 7.Do you have the lastest updates as well as the platform update installed?Am 14.03.2021 18:30 schrieb kubachimaru ***@***.***>:

I cant use any patch later than GD3D11-17.7-dev8 because an error 0xc0000005 appear (Windows 7 Lenovo Ideapad Y700). Why is this so ? If i paste latest patch this error is showing up. If i use an 17.7-dev8 again game is starting with no problem...

**Comment by kubachimaru** [comment]
Yep. Latest updates are there. I noticed that when i use a GD3D11-17.7-dev16 patch and i copy only "ddraw.ddl" from GD3D11-17.7-dev8 (older) and paste it on latest patch game is working again. Old ddraw.ddl work with latest patch making it playable but its not compatible i guess. What is the problem then... Old patch is working and the latest is not.

**Comment by Kirides** [comment]
Sorry but i won't invest time in debugging Windows 7 specific errors.

for once, i don't own any windows 7 computers.
And second, current version even run on Linux with DXVK as some other people tried to run them there.

If someone with a windows 7 dev-machine wants to find the source of the incompatibility, i will gladly accept a pullrequest to restore windows 7 compatibility.
