### ISSUE TITLE
20fps limit-bug

### ISSUE THREAD

**Issue by progward** [Kirides/GD3D11#54]
When playing in window-mode, seemingly random, the fps limit gets set to 20, which I think it only should do when Gothic is running in the background. It wasn't though, so there must be some kind of bug with windowed-mode activated.

**Comment by Kirides** [comment]
Any chance that it happens when you open the F11 Menu?

I know that with an older Union version, there was an issue. Could you please provide more information regarding your system and game setup?


Information about your system

 - dxdiag output - Open windows search and enter "dxdiag" and run it. Press the button "save all information ..." - save the file and upload it together with the issue.  
![grafik](https://user-images.githubusercontent.com/13602143/120205925-d43b4080-c22a-11eb-9db9-0d03ba4fe337.png)


Informations about the Gothic Installation
   - Systempack installed? Which Version? 1.7, ..., 1.8 ?
   - Union?
      - version?
      - also happens with latest version?
   - Any patches installed? (Textures, or similar)
   - Were Mods installated in this installation?
   - Are you playing a mod?
   - Renderer Version? "worked fine with dev2 broken with dev5 started with dev3
   - How did you install the renderer?
     -   best to rename the previous ddraw.dll, as well as the previous GD3D11 directory (e.g. "GD3D11_")



Information regarding issues
- Complete "Gothic\System\Log.txt" of the crashed session. (just the last few lines are NOT sufficient)
    : If the game crashes with an Access Violation - the content is automatically copied into your Clipboard (CTRL+V). Save this into a text-file and upload it aswell.

**Comment by progward** [comment]
Union isn't installed. SystemPack version is 1.8.
Installed the renderer by replacing the content of AppData\Roaming\Clockwork Origins\Spine\mods\209\System with the built build of your latest commit. Playing with the latest GMP version, with an additional .vdf that has improved and new textures.
With Bonne's latest Renderer, this bug isn't existent with the same things mentioned above installed.

**Comment by progward** [comment]
[Uploading DxDiag.txt…]()

**Comment by progward** [comment]
[Log.txt](https://github.com/Kirides/GD3D11/files/6570952/Log.txt)
(Game didn't crash though)

**Comment by progward** [comment]
Bug also isn't present in your latest pre-release version.

**Comment by postm1** [comment]
A bug occurs when I put F11 and menu opens. (Tested in my Spacer.net)

**Comment by postm1** [comment]
I have found the culprit.
[Shadows]SmoothCameraUpdate if 1, it limits fps as 20. 
I have it 1 in userSettings.ini and got 20 fps. I change it to 0 and fps is ok now ;)

**Comment by postm1** [comment]
It has something to do with settings.
When my usersettings.ini is almost empty no bug, if I add settings to that file I got 20 fps.

**Comment by postm1** [comment]
When I clean my usersettings.ini fps goes ok.
When I put there something it is 20...

**Comment by postm1** [comment]
![image](https://user-images.githubusercontent.com/2078377/123833285-df0ef100-d90e-11eb-82c8-f17b6c7b9642.png)
I guess that is it. It thinks that windows is not active I guess

**Comment by postm1** [comment]
Can you add option in ini file to Ignore fps limit when window is not active?

**Comment by Kirides** [comment]
Will do, for the next version. For now, you can use a previous version, without 20 fps limit for inactive game windowAm 29.06.2021 18:20 schrieb proxin ***@***.***>:
Can you add option in ini file to Ignore fps limit when window is not active?

**Comment by postm1** [comment]
Thanks, I rebuild it anyway for Spacer.net (it uses G2 addon addresses, it is a usual game gothic2.exe)
