### ISSUE TITLE
Text render scale problem

### ISSUE THREAD

**Issue by postm1** [Kirides/GD3D11#58]
Hi, in function void **D3D11GraphicsEngine::DrawString** you use 
`if ( oCGame::GetGame() ) {
        UIScale = (float)oCGame::GetGame()->hpBar->psizex / 180;
    }`

Can you get UIScale in another way?
In AB mod there is an option which can move & resize bars.
And after resizing the bars, ingame text does not render due to changing in hpBar->psizex

You can use `UIScale = Engine::GAPI->GetRendererState().RendererSettings.GothicUIScale;` or something like that.
Please, change it if you can ;)

**Comment by Kirides** [comment]
I can not use a static value, as Systempack etc.  might modify perceived UI size. 180 is the regular size of a bar, that gets scaled by Systempack etc. If you have any clue how to get a comparable solution, without having to specify the scaling in different places, or relying on systempack.ini, feel free to write about it.Am 01.07.2021 11:05 schrieb proxin ***@***.***>:
Hi, in function void D3D11GraphicsEngine::DrawString you use
if ( oCGame::GetGame() ) { UIScale = (float)oCGame::GetGame()->hpBar->psizex / 180; }
Can you get UIScale in another way?
In AB mod there is an option which can move & resize bars.
And after resizing the text does not render due to changing in hpBar->psizex.
You can use UIScale = Engine::GAPI->GetRendererState().RendererSettings.GothicUIScale; or something like that.
Please, change it if you can ;)

**Comment by postm1** [comment]
Use the **swimBar** 
`UIScale = (float)oCGame::GetGame()->swimBar->psizex / 180;`
It works fine ;) It has the same size, but no bug occured. :) thanks

**Comment by postm1** [comment]
I tried with swimBar, it works fine. So, please, use it in the next build ;)
