### ISSUE TITLE
Ghost's face in dialogs

### ISSUE THREAD

**Issue by postm1** [kirides/GD3D11#74]
Hi, when you are in a dialog with ghost npc, its face has some errors.
It happens only when npc's animation of speaking is active.

![image](https://user-images.githubusercontent.com/2078377/126991429-d69b6d80-dca3-4f3d-b7cd-10fed44b7282.png)

**Comment by Kirides** [comment]
Will be fixed when @SaiyansKing's current work is merged.

- Fixes & Improvements f30a39f73a37ae231409b4dd217ced480d6baf85
  - Add option to change texture quality
  - Add option to change color backbuffer format to one that use less bandwidth so it can reduce vram usage while compromising image fidelity.
  - Make every mesh use the same CW order so that we don't need to do aby unnecessary state change
  - Use reverse depth buffer to fix most z-fighting issues we are facing
  - Optimize post-processing pipeline and theirs shaders
  - Use 16bit depth buffers for shadowmaps since they don't require full precision
  - Disable painting that zengine might be doing - it fixes the black screen issue in G1 when using advanced settings
  - Enable model scaling in G1
  - Improve dxgi discrete gpu detection.
- Fixes & Improvements 41003193e1d1f884d5a013d73cb86bb0a2781f73
  - Confine mouse cursor inside Gothic window when it's active - when having dual monitor setup it was possible to lose focus on Gothic window when using mouse
  - Fix ghost's facial animation glitch
  - Fix possible zengine integer overflow crash at game startup
  - Setup working directory at game startup so that GD3D11 settings can be loaded correctly when launching game through steam
  - Add Polish translation to the settings for Polish players
- Fix pfx distortion shader to work with reversed depth 78f0e297b4158f2f868e6098456d395fc2381554
- Fixes 6a297ee649bb432c90082505ca645f7c9640ea38
  - Use BGRA format for swapchain since device is created with BGRA support and it'll be transitioned to BGRA anyway
  - Reduce render state changes even more
  - Remove texture precaching for PolyStrip's because GetAniTexture will precache them anyway
  - Fix mobs having wrong texture in some rare casses.
